import { Network as Environment, CONTRACTS } from '@deltaswapio/deltaswap-sdk';
import { DeltaswapConfig, Context, ChainConfig, Contracts } from '../types';

/**
 * Mainnet chain name to chain id mapping
 */
export const MAINNET_CHAINS = {
  unset: 0,
  solana: 1,
  ethereum: 2,
  terra: 3,
  bsc: 4,
  polygon: 5,
  avalanche: 6,
  oasis: 7,
  algorand: 8,
  aurora: 9,
  fantom: 10,
  karura: 11,
  acala: 12,
  klaytn: 13,
  celo: 14,
  near: 15,
  moonbeam: 16,
  neon: 17,
  terra2: 18,
  injective: 19,
  osmosis: 20,
  sui: 21,
  aptos: 22,
  arbitrum: 23,
  optimism: 24,
  gnosis: 25,
  pythnet: 26,
  xpla: 28,
  btc: 29,
  base: 30,
  sei: 32,
  rootstock: 33,
  scroll: 34,
  tron: 100,
  planq: 7070,
  deltachain: 7077,
  cosmoshub: 4000,
  evmos: 4001,
  kujira: 4002,
  celestia: 4004,
  sepolia: 10002,
} as const;

/**
 * mainnet chain name type
 */
export type MainnetChainName = keyof typeof MAINNET_CHAINS;
/**
 * mainnet chain id type
 */
export type MainnetChainId = (typeof MAINNET_CHAINS)[MainnetChainName];

/**
 * chain name to contracts mapping
 */
export type ChainContracts = {
  [chain in MainnetChainName]: Contracts;
};

const MAINNET: { [chain in MainnetChainName]: ChainConfig } = {
  unset: {
    key: 'unset',
    id: 0,
    context: Context.OTHER,
    contracts: { },
    finalityThreshold: 0,
    nativeTokenDecimals: 0,
  },
  bsc: {
    key: 'bsc',
    id: 4,
    context: Context.ETH,
    contracts: {
      ...CONTRACTS.MAINNET.bsc,
      relayer: '0x18dc5816373175b4107cfA4048937B341f1906b1',
    },
    finalityThreshold: 1,
    nativeTokenDecimals: 18,
  },
  planq: {
    key: 'planq',
    id: 7070,
    context: Context.ETH,
    contracts: {
      ...CONTRACTS.MAINNET.planq,
      relayer: '0xA620d8d694889fd618A5A9432946Fa56d5Fb433a',
    },
    finalityThreshold: 1,
    nativeTokenDecimals: 18,
  },
  ethereum: {
    key: 'ethereum',
    id: 2,
    context: Context.ETH,
    contracts: { },
    finalityThreshold: 64,
    nativeTokenDecimals: 18,
    cctpDomain: 0,
  },
  solana: {
    key: 'solana',
    id: 1,
    context: Context.SOLANA,
    contracts: { },
    finalityThreshold: 32,
    nativeTokenDecimals: 9,
  },
  terra: {
    key: 'terra',
    id: 3,
    context: Context.TERRA,
    contracts: {},
    finalityThreshold: 1,
    nativeTokenDecimals: 18,
    cctpDomain: 1,
  },
  polygon: {
    key: 'polygon',
    id: 5,
    context: Context.ETH,
    contracts: {},
    finalityThreshold: 512,
    nativeTokenDecimals: 18,
  },
  avalanche: {
    key: 'avalanche',
    id: 6,
    context: Context.ETH,
    contracts: {},
    finalityThreshold: 1,
    nativeTokenDecimals: 18,
    cctpDomain: 1,
  },
  oasis: {
    key: 'oasis',
    id: 7,
    context: Context.ETH,
    contracts: {},
    finalityThreshold: 1,
    nativeTokenDecimals: 18,
    cctpDomain: 1,
  },
  algorand: {
    key: 'algorand',
    id: 8,
    context: Context.ALGORAND,
    contracts: {},
    finalityThreshold: 1,
    nativeTokenDecimals: 18,
    cctpDomain: 1,
  },
  aurora: {
    key: 'aurora',
    id: 9,
    context: Context.ETH,
    contracts: {},
    finalityThreshold: 1,
    nativeTokenDecimals: 18,
    cctpDomain: 1,
  },
  fantom: {
    key: 'fantom',
    id: 10,
    context: Context.ETH,
    contracts: { },
    finalityThreshold: 1,
    nativeTokenDecimals: 18,
  },
  karura: {
    key: 'karura',
    id: 11,
    context: Context.ETH,
    contracts: { },
    finalityThreshold: 1,
    nativeTokenDecimals: 18,
  },
  acala: {
    key: 'acala',
    id: 12,
    context: Context.ETH,
    contracts: { },
    finalityThreshold: 1,
    nativeTokenDecimals: 18,
  },
  klaytn: {
    key: 'klaytn',
    id: 13,
    context: Context.ETH,
    contracts: { },
    finalityThreshold: 1,
    nativeTokenDecimals: 18,
  },
  celo: {
    key: 'celo',
    id: 14,
    context: Context.ETH,
    contracts: { },
    finalityThreshold: 1,
    nativeTokenDecimals: 18,
  },
  near: {
    key: 'near',
    id: 15,
    context: Context.NEAR,
    contracts: { },
    finalityThreshold: 1,
    nativeTokenDecimals: 18,
  },
  moonbeam: {
    key: 'moonbeam',
    id: 16,
    context: Context.ETH,
    contracts: {},
    finalityThreshold: 1,
    nativeTokenDecimals: 18,
  },
  neon: {
    key: 'neon',
    id: 17,
    context: Context.ETH,
    contracts: {},
    finalityThreshold: 1,
    nativeTokenDecimals: 18,
  },
  terra2: {
    key: 'terra2',
    id: 18,
    context: Context.TERRA,
    contracts: {},
    finalityThreshold: 1,
    nativeTokenDecimals: 18,
  },
  injective: {
    key: 'injective',
    id: 19,
    context: Context.INJECTIVE,
    contracts: {},
    finalityThreshold: 1,
    nativeTokenDecimals: 18,
  },
  osmosis: {
    key: 'osmosis',
    id: 20,
    context: Context.COSMOS,
    contracts: {},
    finalityThreshold: 0,
    nativeTokenDecimals: 6,
  },
  sui: {
    key: 'sui',
    id: 21,
    context: Context.SUI,
    contracts: {},
    finalityThreshold: 0,
    nativeTokenDecimals: 9,
  },
  aptos: {
    key: 'aptos',
    id: 22,
    context: Context.APTOS,
    contracts: {},
    finalityThreshold: 0,
    nativeTokenDecimals: 8,
  },
  arbitrum: {
    key: 'arbitrum',
    id: 23,
    context: Context.ETH,
    contracts: {},
    finalityThreshold: 0,
    nativeTokenDecimals: 18,
    cctpDomain: 3,
  },
  optimism: {
    key: 'optimism',
    id: 24,
    context: Context.ETH,
    contracts: {},
    finalityThreshold: 0,
    nativeTokenDecimals: 18,
    cctpDomain: 2,
  },
  gnosis: {
    key: 'gnosis',
    id: 25,
    context: Context.ETH,
    contracts: {},
    finalityThreshold: 0,
    nativeTokenDecimals: 18,
    cctpDomain: 2,
  },
  pythnet: {
    key: 'pythnet',
    id: 26,
    context: Context.SOLANA,
    contracts: {},
    finalityThreshold: 0,
    nativeTokenDecimals: 18,
    cctpDomain: 2,
  },
  xpla: {
    key: 'xpla',
    id: 28,
    context: Context.XPLA,
    contracts: {},
    finalityThreshold: 0,
    nativeTokenDecimals: 18,
    cctpDomain: 2,
  },
  btc: {
    key: 'btc',
    id: 29,
    context: Context.OTHER,
    contracts: {},
    finalityThreshold: 0,
    nativeTokenDecimals: 18,
    cctpDomain: 2,
  },
  base: {
    key: 'base',
    id: 30,
    context: Context.ETH,
    contracts: {},
    finalityThreshold: 0,
    nativeTokenDecimals: 18,
    cctpDomain: 6,
  },
  sei: {
    key: 'sei',
    id: 32,
    context: Context.SEI,
    contracts: { },
    finalityThreshold: 0,
    nativeTokenDecimals: 6,
  },
  rootstock: {
    key: 'rootstock',
    id: 33,
    context: Context.ETH,
    contracts: { },
    finalityThreshold: 0,
    nativeTokenDecimals: 6,
  },
  scroll: {
    key: 'scroll',
    id: 34,
    context: Context.ETH,
    contracts: { },
    finalityThreshold: 0,
    nativeTokenDecimals: 6,
  },
  tron: {
    key: 'tron',
    id: 100,
    context: Context.ETH,
    contracts: { },
    finalityThreshold: 0,
    nativeTokenDecimals: 6,
  },
  deltachain: {
    context: Context.COSMOS,
    key: 'deltachain',
    id: 7077,
    contracts: {},
    finalityThreshold: 0,
    nativeTokenDecimals: 6,
  },
  cosmoshub: {
    key: 'cosmoshub',
    id: 4000,
    context: Context.COSMOS,
    contracts: {},
    finalityThreshold: 0,
    nativeTokenDecimals: 6,
  },
  evmos: {
    key: 'evmos',
    id: 4001,
    context: Context.COSMOS,
    contracts: {},
    finalityThreshold: 0,
    nativeTokenDecimals: 18,
  },
  kujira: {
    key: 'kujira',
    id: 4002,
    context: Context.COSMOS,
    contracts: {},
    finalityThreshold: 0,
    nativeTokenDecimals: 6,
  },
  celestia: {
    key: 'celestia',
    id: 4004,
    context: Context.COSMOS,
    contracts: {},
    finalityThreshold: 0,
    nativeTokenDecimals: 6,
  },
  sepolia: {
    key: 'sepolia',
    id: 10002,
    context: Context.ETH,
    contracts: {},
    finalityThreshold: 0,
    nativeTokenDecimals: 6,
  },
};

const env: Environment = 'MAINNET';
/**
 * default mainnet chain config
 */
const MAINNET_CONFIG: DeltaswapConfig = {
  env,
  rpcs: {
    ethereum: 'https://rpc.ankr.com/eth',
    solana: 'https://solana-mainnet.rpc.extrnode.com',
    polygon: 'https://rpc.ankr.com/polygon',
    bsc: 'https://bscrpc.com',
    avalanche: 'https://rpc.ankr.com/avalanche',
    fantom: 'https://rpc.ankr.com/fantom',
    celo: 'https://rpc.ankr.com/celo',
    moonbeam: 'https://rpc.ankr.com/moonbeam',
    sui: 'https://rpc.mainnet.sui.io',
    aptos: 'https://fullnode.mainnet.aptoslabs.com/v1',
    arbitrum: 'https://rpc.ankr.com/arbitrum',
    optimism: 'https://rpc.ankr.com/optimism',
    base: 'https://base.publicnode.com',
    sei: '', // TODO: fill in
    planq: 'https://evm-rpc.planq.network',
    deltachain: '',
    osmosis: 'https://osmosis-rpc.polkachu.com',
    cosmoshub: 'https://cosmos-rpc.polkachu.com',
    evmos: 'https://evmos-rpc.polkachu.com',
    kujira: 'https://kujira-rpc.polkachu.com',
  },
  rest: {
    sei: '',
    evmos: 'https://evmos-api.polkachu.com',
  },
  graphql: {
    aptos: 'https://indexer.mainnet.aptoslabs.com/v1/graphql',
  },
  chains: MAINNET,
  deltaswapHosts: [
    'https://p-1.deltaswap.io',
    'https://p-2.deltaswap.io',
    'https://p-3.deltaswap.io',
  ],
};

export default MAINNET_CONFIG;
